version: "3"
services:
  mysql:
    image: "mysql:latest"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "superhardpassword"
      MYSQL_DATABASE: "crud"
      MYSQL_USER: "crud_api"
      MYSQL_PASSWORD: "superpassword"
    volumes:
      - /home/nix/database/mysql:/var/lib/mysql
  api:
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "3979:3979"
    depends_on:
      - mysql
    environment:
      PORT: 3979
      NODE_ENV: "development"
      TYPEORM_CONNECTION: "mysql"
      TYPEORM_HOST: mysql
      TYPEORM_USERNAME: "crud_api"
      TYPEORM_PASSWORD: "superpassword"
      TYPEORM_DATABASE: "crud"
      TYPEORM_PORT: 3306
      TYPEORM_ENTITIES: "dist/entity/*.js"
      TYPEORM_MIGRATIONS_DIR: "src/migration"
      TYPEORM_MIGRATIONS: "dist/migration/*.js"
